# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frigoDemo' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frigoDemo

  

  platform :ios, '9.0'
  target 'frigoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'frigoDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frigoDemo-tvOS

  target 'frigoDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
